export const FETCH_CATEGORY_PENDING = 'FETCH_CATEGORY_PENDING';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR';
export const FETCH_CATEGORY_DELETE_SUCCESS = 'FETCH_CATEGORY_DELETE_SUCCESS';
export const CATEGORY_ADD_DATA = 'CATEGORY_ADD_DATA';
export const CATEGORY_EDIT_DATA = 'CATEGORY_EDIT_DATA';
export const CATEGORY_UPDATE_DATA = 'CATEGORY_UPDATE_DATA';


export const FETCH_PRODUCT_PENDING = 'FETCH_PRODUCT_PENDING';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';
export const FETCH_PRODUCT_DELETE_SUCCESS = 'FETCH_PRODUCT_DELETE_SUCCESS';